In [25]:
import torch
x=torch.rand(5,3)
print(x)

x=torch.zeros(5,3,dtype=torch.long)
print(x)

x=torch.tensor([5.5,3])
print(x)

x=x.new_ones(5,3,dtype=torch.float64)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)

print(x.shape)
print(x.size())



y=torch.rand(5,3)
print(x+y)

print(torch.add(x,y))

result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

y.add_(x)
print(y)

y=x[0,:]
y+=1
print(y)
print(x[0,:])

x=torch.ones(2,2)

y=x[0,:]
print(x)
print(y)

y+=1
print(y)

print(x)

y=x.view(4)
print(x)
print(y)

z=x.view(4,-1)

print(z)

tensor([[0.3379, 0.3739, 0.9709],
        [0.6044, 0.6602, 0.6570],
        [0.6101, 0.9028, 0.3004],
        [0.2928, 0.7362, 0.3836],
        [0.2294, 0.3503, 0.3473]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3436,  0.7922,  1.0876],
        [-0.4078, -0.6274, -0.0199],
        [-0.7777,  1.9172, -0.7599],
        [-0.7295, -0.1523,  0.8726],
        [-0.2742, -0.5976, -0.6920]])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 1.3377,  1.1176,  1.2527],
        [ 0.1887, -0.1481,  0.4496],
        [ 0.0189,  2.6188, -0.6038],
        [-0.5860,  0.3909,  1.7516],
        [ 0.5835,  0.0821,  0.1677]])
tensor([[ 1.3377,  1.1176,  1.2527],
        [ 0.1887, -0.1481,  0.4496],
        [ 0.0189,  2.6188, -0.6038],
        [-0.5860,  0.3909,  1.7516],
        [ 0.5835, 

In [26]:
x+=1
print(x)
print(y)

tensor([[3., 3.],
        [2., 2.]])
tensor([3., 3., 2., 2.])


In [28]:
x_cp=x.clone().view(4)
x-=1
print(x)
print(x_cp)

tensor([[2., 2.],
        [1., 1.]])
tensor([3., 3., 2., 2.])


In [29]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.8962])
-0.896202802658081


In [31]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [35]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y[:]=y+x
print(id(y)==id_before)

True


In [36]:
a=torch.ones(5)
b=a.numpy()
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [37]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)
a+=1
print(a,b)
b+=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [38]:
c=torch.tensor(a)
a+=1;
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
